 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/branch_links", type: :request do
  
  # BranchLink. As you add validations to BranchLink, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BranchLink.create! valid_attributes
      get branch_links_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      branch_link = BranchLink.create! valid_attributes
      get branch_link_url(branch_link)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_branch_link_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      branch_link = BranchLink.create! valid_attributes
      get edit_branch_link_url(branch_link)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BranchLink" do
        expect {
          post branch_links_url, params: { branch_link: valid_attributes }
        }.to change(BranchLink, :count).by(1)
      end

      it "redirects to the created branch_link" do
        post branch_links_url, params: { branch_link: valid_attributes }
        expect(response).to redirect_to(branch_link_url(BranchLink.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BranchLink" do
        expect {
          post branch_links_url, params: { branch_link: invalid_attributes }
        }.to change(BranchLink, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post branch_links_url, params: { branch_link: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested branch_link" do
        branch_link = BranchLink.create! valid_attributes
        patch branch_link_url(branch_link), params: { branch_link: new_attributes }
        branch_link.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the branch_link" do
        branch_link = BranchLink.create! valid_attributes
        patch branch_link_url(branch_link), params: { branch_link: new_attributes }
        branch_link.reload
        expect(response).to redirect_to(branch_link_url(branch_link))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        branch_link = BranchLink.create! valid_attributes
        patch branch_link_url(branch_link), params: { branch_link: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested branch_link" do
      branch_link = BranchLink.create! valid_attributes
      expect {
        delete branch_link_url(branch_link)
      }.to change(BranchLink, :count).by(-1)
    end

    it "redirects to the branch_links list" do
      branch_link = BranchLink.create! valid_attributes
      delete branch_link_url(branch_link)
      expect(response).to redirect_to(branch_links_url)
    end
  end
end
