 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tag_links", type: :request do
  
  # TagLink. As you add validations to TagLink, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TagLink.create! valid_attributes
      get tag_links_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tag_link = TagLink.create! valid_attributes
      get tag_link_url(tag_link)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tag_link_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      tag_link = TagLink.create! valid_attributes
      get edit_tag_link_url(tag_link)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TagLink" do
        expect {
          post tag_links_url, params: { tag_link: valid_attributes }
        }.to change(TagLink, :count).by(1)
      end

      it "redirects to the created tag_link" do
        post tag_links_url, params: { tag_link: valid_attributes }
        expect(response).to redirect_to(tag_link_url(TagLink.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TagLink" do
        expect {
          post tag_links_url, params: { tag_link: invalid_attributes }
        }.to change(TagLink, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post tag_links_url, params: { tag_link: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tag_link" do
        tag_link = TagLink.create! valid_attributes
        patch tag_link_url(tag_link), params: { tag_link: new_attributes }
        tag_link.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the tag_link" do
        tag_link = TagLink.create! valid_attributes
        patch tag_link_url(tag_link), params: { tag_link: new_attributes }
        tag_link.reload
        expect(response).to redirect_to(tag_link_url(tag_link))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        tag_link = TagLink.create! valid_attributes
        patch tag_link_url(tag_link), params: { tag_link: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tag_link" do
      tag_link = TagLink.create! valid_attributes
      expect {
        delete tag_link_url(tag_link)
      }.to change(TagLink, :count).by(-1)
    end

    it "redirects to the tag_links list" do
      tag_link = TagLink.create! valid_attributes
      delete tag_link_url(tag_link)
      expect(response).to redirect_to(tag_links_url)
    end
  end
end
